ArthurL808/consume-more-stuff

database/migrations/20191023213816_create_itemStatuses.js
made basic schema for itemStatuses table may need changes in the future for stretch goals.
=> made itemStatuses table migration

database/migrations/20191023205531_create-items.js, database/migrations/20191023213254_create-categories.js
Category migration table is finished, only 2 parameters needed
=> Making category table migration

database/migrations/20191023205531_create-items.js, database/migrations/20191023213254_create-categories.js, database/migrations/20191024102339_create_userStatuses.js, database/models/UserStatuses.js, database/seeds/userStatuses.js
made migration called userStatuses
=> Models for users statuses

database/migrations/20191023205531_create-items.js, database/migrations/20191023213254_create-categories.js, database/migrations/20191023215833_create_conditions.js, database/models/Conditions.js, database/seeds/conditions.js
made a basic schema for conditions table may need to make changes later but i doubt it
=> Models for conditions

database/migrations/20191023213816_create_itemStatuses.js, database/models/ItemStatuses.js, database/seeds/itemStatuses.js
changed name column in itemStatuses from 'name' to status to try to eliminate some confusion later in development
=> made seed and model for itemStatuses also changed name column

src/Components/Sidebar/Sidebar.jsx, src/Components/Sidebar/Sidebar.module.scss, src/index.scss
1.Changes the content of the sidebar for auth and unauth views to match the layout given by the client
2. If the user if auth then the sidebar will show the first list view, if they are not then it will show the second list view
=> Font end sidebar

database/migrations/20191023205531_create-items.js, database/migrations/20191024184532_create-users.js, database/models/Category.js, database/models/Item.js, database/models/User.js
=> Making users tables

database/migrations/20191023213254_create-categories.js, database/seeds/categories.js, database/seeds/users.js
=> Making seed for users

package-lock.json, package.json, src/App.js, src/Components/Header/Header.jsx, src/Components/Header/Header.module.scss, src/Components/MainBody/MainBody.jsx, src/Components/MainBody/MainBody.module.scss, src/Components/Sidebar/Sidebar.jsx, src/Components/Sidebar/Sidebar.module.scss, src/Components/UnAuth/UnAuth.jsx, src/Components/UnAuth/UnAuth.module.scss, src/Components/UnAuth/index.js, src/Components/UnAuthAll/UnAuthAll.jsx, src/Components/UnAuthAll/index.js, src/Components/UnAuthAppliances/UnAuthAppliances.jsx, src/Components/UnAuthAppliances/index.js, src/Components/UnAuthComputers/UnAuthComputers.jsx, src/Components/UnAuthComputers/index.js, src/Components/UnAuthFurniture/UnAuthFurniture.jsx, src/Components/UnAuthFurniture/index.js, src/Components/UnAuthVehicles/UnAuthVehicles.jsx, src/Components/UnAuthVehicles/index.js, src/Routes.js
1. Creates the routes for the unauth section
2. - uses react-router-down to create routes that load in the component of whatever link is clicked on in the sidebar
=> Unauth view

server/database/decorator.js, server/routes/api/index.js, server/routes/api/items/items.js, server/server.js
localhost:8080/api/items smoke test working
=> making item route, smoke test works

package-lock.json, package.json, server/routes/api/users/users.js, src/Components/App/App.js, src/Components/UnAuth/UnAuthAll/UnAuthAll.jsx, src/actions/index.js, src/index.js, src/reducers/index.js
made basic CRUD routes for users will need to make changes later when we implement auth
=> User routes

package-lock.json, package.json, src/Components/App/App.js, src/Components/UnAuth/UnAuthAll/UnAuthAll.jsx, src/actions/index.js, src/index.js, src/reducers/index.js
1. Pulls data from the backend to the unAuthAll view 
2. Uses redux and useEffect to call the items
=> Checking end to end

server/routes/api/items/items.js
=> Making basic crud routes for items, working

src/Components/App/App.js, src/Components/App/App.module.scss, src/Components/Header/Header.jsx, src/Components/Header/Header.module.scss, src/Components/MainBody/MainBody.module.scss, src/Components/Sidebar/Sidebar.jsx, src/Components/Sidebar/Sidebar.module.scss, src/actions/index.js, src/index.scss
1. Makes sidebar responsive with animations
2.  - Adds toggle animation using react spring
- Creates a show/hide btn that toggles the sidebar on on mobile
- Adds a function within useEffect that only toggles the animation at a certain breakpoint
=> Front end styles

src/Components/App/App.js, src/Components/Sidebar/Sidebar.module.scss, src/Components/TopBar/TopBar.jsx, src/Components/TopBar/TopBar.module.scss, src/Components/TopBar/index.js
1. Fixes sidebar issues
2.  Creates a sidebar and a topbar and disables them depending on the screen width
=> Sidebar fix

server/database/seeds/3_itemStatuses.js, src/Components/Auth/AuthHome/AuthHome.jsx, src/Components/Auth/AuthHome/AuthHomeFilter/AuthHomeFilter.jsx
1) authorized home view is now showing items by item status filter from backend. 
2) the filter is hardcoded though since I can only pull the item status ID instead of the actual status.
=> filter now working on auth home

src/Components/App/App.js
1. Allows content dynamically change for the topbar depending on the the login status
2. Passes the isAuth state as a prop to the topbar so it knows the login status
=> passes isAuth to the topbar to allow different content

src/Components/App/App.js, src/Components/Filter/Filter.jsx, src/Components/Filter/Filter.module.scss, src/Components/Filter/index.js, src/Components/ProductRow/ProductRow.jsx, src/Components/ProductRow/ProductRow.module.scss, src/Components/ProductRow/index.js, src/Components/UnAuth/UnAuthAll/UnAuthAll.jsx
1. Creates global filter component 
2. Makes filter component that maps through all the items and returns the items that match the filter keyword
=> Unauhth views

src/actions/index.js, src/reducers/index.js
not sure if it works properly yet though still needs to be tested
=> made ADD_ITEM action

src/Components/Filter/Filter.jsx
fixes spacing issue with the images
=> Un auth images

server/routes/api/items/items.js
it into our "/new" post route in the same file
=> got rid of image-upload post route in items and intergrated 

src/Components/App/App.js, src/Components/Auth/AuthNewItem/AuthNewItem.jsx
Sends that data for the form back a json once it's submitted
=> New item form

src/Components/Auth/AuthEditItem/AuthEditItem.jsx, src/Components/Auth/AuthEditItem/index.js, src/Components/Auth/AuthHome/AuthHomeFilter/AuthHomeFilter.jsx, src/Routes.js
Created edit item page component skeleton and added route /path for it.
=> created new route for detailed item and made edit item component

server/routes/api/items/items.js, server/routes/api/users/users.js, src/Components/Auth/AuthHome/AuthHomeFilter/AuthHomeFilter.jsx, src/Components/UnAuth/UnAuth.jsx, src/actions/index.js, src/index.js, src/reducers/index.js, src/reducers/itemsReducer.js, src/reducers/singleItemReducer.js
i hope this all works please let me know if i messed up
=> Single item reducers and actions

src/Components/App/App.js, src/Components/Header/Header.jsx, src/Components/LoginForm/LoginForm.js, src/Components/LoginForm/LoginForm.module.scss, src/Components/LoginForm/index.js
**Creates a login form**
-  makes a login form component that fades in an out while it toggles
- asks for username and password and has an option for new users to sign up if they don't have an account already that takes in their email
=> Login form

src/Components/Auth/AuthHome/AuthHome.jsx, src/Components/Auth/AuthHome/AuthHome.module.scss, src/Components/Auth/AuthHomeFilter/AuthHomeFilter.module.scss
Gets rid of the entire AuthFilter scrolling hoziontally throughout the page
=> fixes the sidescroll issue

src/Components/Auth/AuthDetailItem/AuthDetailItem.jsx, src/Components/Auth/AuthNewItem/AuthNewItem.jsx
Using single item reducer to display detailed item page. 
Added a go back button to return to home.
=> item detail page showing properly

src/Components/Auth/AuthNewItem/AuthNewItem.jsx, src/Components/Auth/AuthNewItem/AuthNewItem.module.scss, src/Components/UnAuth/UnAuth.module.scss
updates styles for the login form
=> updates styles

src/Components/Auth/AuthDetailItem/AuthDetailItem.jsx, src/Components/Auth/AuthEditItem/AuthEditItem.jsx, src/Components/Auth/AuthHomeFilter/AuthHomeFilter.jsx
Added created and updated time in UTC string format on detailed item page.
Added edit button to show edit component, need to still create edit form.
=> adding more to detail item page

server/database/seeds/2_conditions.js, server/routes/api/items/items.js, src/Components/Auth/AuthNewItem/AuthNewItem.jsx, src/actions/index.js
i hope this does not break >.<
=> finally got post to work with s3

server/routes/api/items/items.js, src/Components/UnAuth/UnAuth.jsx
for some reason after I post a new item and try to go back to the home page it breaks and needs to be refreshed to see new items. need to find out how to fix that later
=> fixed post to account for items without images

src/Components/Auth/AuthDetailItem/AuthDetailItem.jsx, src/Components/Auth/AuthDetailItem/AuthDetailItem.module.scss
Changing layout/view of item detail page. Still working progress.
=> adding some css

src/Components/Auth/AuthDetailItem/AuthDetailItem.jsx, src/Components/Auth/AuthDetailItem/AuthDetailItem.module.scss
Changed some stuff on detail item page.
=> Auth detail item rina

src/Components/Auth/AuthDetailItem/AuthDetailItem.jsx, src/Components/Auth/AuthHome/AuthHome.jsx, src/Components/MainBody/MainBody.jsx, src/Components/UnAuthDetailItem/UnAuthDetailItem.jsx
gets rid of warning with in the console
=> gets rid of warnings
